[2018-09-28 00:13:04,123][Thread-1:123145326198784][task_id:django.request][log.py:228][WARNING][Not Found: /reset/ntuIjkdTRfiS4wyDQ3GTu35oEn6KQLe9/]
[2018-09-28 00:15:11,622][Thread-4:123145529409536][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/forget/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 155, in post
    send_register_email(email, "forget")
  File "/Users/sugyil/dashubao/utils/email_send.py", line 59, in send_register_email
    url = reverse('users:users_reset', args=[code])
NameError: name 'reverse' is not defined
[2018-09-28 00:49:20,843][Thread-1:123145384525824][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/forget/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sugyil/dashubao/dashubao/mobileurls.py", line 15, in <module>
    ('users.mobileurls', 'users'), namespace="users")),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sugyil/dashubao/apps/users/mobileurls.py", line 3, in <module>
    from users import views
  File "/Users/sugyil/dashubao/apps/users/views.py", line 20, in <module>
    from utils.email_send import send_register_email
  File "/Users/sugyil/dashubao/utils/email_send.py", line 60
    send_mail(email_title, body='', settings.EMAIL_FROM, [email],html='<div>444</div>')
                                   ^
SyntaxError: positional argument follows keyword argument
[2018-09-28 00:52:02,339][Thread-4:123145361711104][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/forget/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 155, in post
    send_register_email(email, "forget")
  File "/Users/sugyil/dashubao/utils/email_send.py", line 60, in send_register_email
    send_mail(subject = email_title, from_email=settings.EMAIL_FROM, recipient_list=[email],html='<div>444</div>')
TypeError: send_mail() missing 1 required positional argument: 'body'
[2018-09-28 01:21:22,797][Thread-7:123145448931328][task_id:django.request][log.py:228][WARNING][Not Found: //users/reset/nbhK9FkxgeVGjp1HycgW8D49tlOJzGVf/]
[2018-09-28 01:21:29,410][Thread-8:123145454186496][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/reset/nbhK9FkxgeVGjp1HycgW8D49tlOJzGVf/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 176, in get
    'active_code': active_code})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashubao/p/password_reset.html
[2018-09-28 01:21:46,465][Thread-10:123145448931328][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/reset/nbhK9FkxgeVGjp1HycgW8D49tlOJzGVf/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 176, in get
    'active_code': active_code})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashubao/p/password_reset.html
[2018-09-28 02:48:33,288][Thread-3:123145484931072][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 02:48:33,370][Thread-5:123145484931072][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 02:48:33,380][Thread-4:123145479675904][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 02:48:33,392][Thread-6:123145490186240][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 02:48:33,405][Thread-7:123145495441408][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 02:48:33,414][Thread-8:123145479675904][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 02:48:36,754][Thread-10:123145484931072][task_id:django.request][log.py:228][WARNING][Not Found: /novel_historybookshelf/oldfenmian/0/635/635s.jpg]
[2018-09-28 02:48:39,050][Thread-12:123145484931072][task_id:django.request][log.py:228][WARNING][Not Found: /novel_sortlist/0/oldfenmian/0/641/641s.jpg]
[2018-09-28 02:48:39,074][Thread-13:123145479675904][task_id:django.request][log.py:228][WARNING][Not Found: /novel_sortlist/0/oldfenmian/0/638/638s.jpg]
[2018-09-28 02:48:39,107][Thread-14:123145484931072][task_id:django.request][log.py:228][WARNING][Not Found: /novel_sortlist/0/oldfenmian/0/635/635s.jpg]
[2018-09-28 02:48:39,115][Thread-15:123145490186240][task_id:django.request][log.py:228][WARNING][Not Found: /novel_sortlist/0/oldfenmian/0/633/633s.jpg]
[2018-09-28 02:48:39,116][Thread-16:123145495441408][task_id:django.request][log.py:228][WARNING][Not Found: /novel_sortlist/0/oldfenmian/0/631/631s.jpg]
[2018-09-28 02:48:39,130][Thread-17:123145500696576][task_id:django.request][log.py:228][WARNING][Not Found: /novel_sortlist/0/oldfenmian/0/630/630s.jpg]
[2018-09-28 02:55:54,269][Thread-1:123145507237888][task_id:django.request][log.py:228][WARNING][Not Found: //users/reset/KFLJbtlMIjolFzz6lskFd5nsZHDZJ7yc/]
[2018-09-28 02:56:17,860][Thread-7:123145512493056][task_id:django.request][base.py:93][WARNING][Method Not Allowed (GET): /operation/modifypwd/]
[2018-09-28 02:56:17,860][Thread-7:123145512493056][task_id:django.request][log.py:228][WARNING][Method Not Allowed: /operation/modifypwd/]
[2018-09-28 03:09:03,535][Thread-4:123145446731776][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:09:08,005][Thread-6:123145451986944][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:09:16,931][Thread-7:123145446731776][task_id:django.request][base.py:93][WARNING][Method Not Allowed (GET): /users/modifypwd/]
[2018-09-28 03:09:16,931][Thread-7:123145446731776][task_id:django.request][log.py:228][WARNING][Method Not Allowed: /users/modifypwd/]
[2018-09-28 03:09:42,176][Thread-12:123145451986944][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:09:42,264][Thread-13:123145446731776][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:09:42,275][Thread-14:123145451986944][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:09:42,285][Thread-15:123145457242112][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:09:42,305][Thread-16:123145446731776][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:09:42,315][Thread-17:123145462497280][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:09:46,434][Thread-22:123145451986944][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:10:11,020][Thread-31:123145446731776][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:14:03,095][Thread-44:123145451986944][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:14:46,117][Thread-46:123145451986944][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:14:51,621][Thread-49:123145446731776][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:15:36,211][Thread-52:123145446731776][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:24:54,885][Thread-5:123145509801984][task_id:django.request][log.py:228][ERROR][Internal Server Error: /operation/adduserfav/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/operation/views.py", line 101, in post
    if exist_records.chapterid == chapterid:
AttributeError: 'QuerySet' object has no attribute 'chapterid'
[2018-09-28 03:29:22,409][Thread-3:123145569206272][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:29:28,789][Thread-7:123145569206272][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:47:02,459][Thread-3:123145383268352][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:47:06,757][Thread-6:123145378013184][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:47:06,845][Thread-7:123145378013184][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:47:06,870][Thread-8:123145383268352][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:47:06,891][Thread-9:123145378013184][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:47:06,899][Thread-10:123145388523520][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:47:06,906][Thread-11:123145393778688][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:47:24,821][Thread-23:123145378013184][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:49:52,418][Thread-3:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:49:52,530][Thread-4:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:49:52,571][Thread-5:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:49:52,582][Thread-6:123145325854720][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:49:52,593][Thread-8:123145336365056][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:49:52,602][Thread-7:123145331109888][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:49:54,334][Thread-10:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /info-641/oldfenmian/0/641/641s.jpg]
[2018-09-28 03:50:59,588][Thread-19:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:51:01,900][Thread-22:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:51:01,987][Thread-23:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:51:02,012][Thread-24:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:51:02,024][Thread-25:123145325854720][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:51:02,036][Thread-26:123145331109888][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:51:02,050][Thread-27:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:51:02,059][Thread-28:123145336365056][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:51:17,374][Thread-30:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:51:17,472][Thread-31:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:51:17,479][Thread-32:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:51:17,493][Thread-33:123145325854720][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:51:17,511][Thread-34:123145331109888][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:51:17,523][Thread-35:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:51:17,535][Thread-36:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:51:44,231][Thread-44:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:51:46,392][Thread-46:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:51:48,194][Thread-48:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:51:57,527][Thread-51:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:51:57,630][Thread-52:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:51:57,642][Thread-53:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:51:57,657][Thread-54:123145325854720][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:51:57,669][Thread-55:123145331109888][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:51:57,677][Thread-56:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:52:00,724][Thread-58:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:52:00,767][Thread-59:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:52:00,824][Thread-60:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:52:00,857][Thread-61:123145320599552][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:52:00,862][Thread-62:123145315344384][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:52:00,882][Thread-63:123145325854720][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:56:38,881][Thread-3:123145399484416][task_id:django.request][log.py:228][WARNING][Not Found: /info-635/oldfenmian/0/635/635s.jpg]
[2018-09-28 03:56:48,135][Thread-10:123145394229248][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:56:53,602][Thread-13:123145394229248][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:56:53,665][Thread-14:123145394229248][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:56:53,706][Thread-15:123145394229248][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:56:53,715][Thread-16:123145399484416][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:56:53,725][Thread-17:123145404739584][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:56:53,735][Thread-18:123145409994752][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:56:56,297][Thread-20:123145399484416][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:56:56,357][Thread-21:123145394229248][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:56:56,366][Thread-23:123145404739584][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:56:56,373][Thread-22:123145399484416][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:56:56,392][Thread-24:123145409994752][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:56:56,401][Thread-25:123145394229248][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:58:38,211][Thread-3:123145535860736][task_id:django.request][log.py:228][WARNING][Not Found: /info-641/oldfenmian/0/641/641s.jpg]
[2018-09-28 03:58:51,796][Thread-10:123145530605568][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 03:58:55,711][Thread-13:123145530605568][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 03:58:55,771][Thread-14:123145530605568][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 03:58:55,806][Thread-15:123145530605568][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 03:58:55,829][Thread-16:123145535860736][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 03:58:55,839][Thread-17:123145541115904][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 03:58:55,851][Thread-18:123145546371072][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 03:58:55,858][Thread-19:123145530605568][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 04:13:03,237][Thread-3:123145443471360][task_id:django.request][log.py:228][WARNING][Not Found: /info-641/oldfenmian/0/641/641s.jpg]
[2018-09-28 04:13:03,540][Thread-5:123145438216192][task_id:django.request][log.py:228][WARNING][Not Found: /info-641/oldfenmian/0/641/641s.jpg]
[2018-09-28 04:13:13,004][Thread-11:123145438216192][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/login/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 90, in post
    if user.is_active:
AttributeError: 'CustomBackend' object has no attribute 'is_active'
[2018-09-28 04:24:23,940][Thread-8:123145471692800][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/login/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 71, in post
    user = modelhelp.authenticate(username=user_name, password=pass_word)
TypeError: authenticate() missing 1 required positional argument: 'self'
[2018-09-28 04:25:02,477][Thread-13:123145408868352][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 04:28:40,070][Thread-10:123145355272192][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 04:28:40,101][Thread-11:123145360527360][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 04:28:40,107][Thread-12:123145365782528][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 04:28:40,109][Thread-14:123145376292864][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 04:28:40,113][Thread-13:123145371037696][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 04:28:40,119][Thread-15:123145381548032][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 16:46:09,482][Thread-21:123145381949440][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 16:46:51,641][Thread-36:123145381949440][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 16:46:51,761][Thread-39:123145392459776][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 16:46:51,757][Thread-41:123145402970112][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 16:46:51,769][Thread-40:123145397714944][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 16:46:51,778][Thread-45:123145376694272][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 16:46:51,788][Thread-38:123145387204608][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 16:47:49,597][Thread-81:123145376694272][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 17:08:37,569][Thread-8:123145411100672][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 17:34:40,993][Thread-17:123145510502400][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 17:34:44,413][Thread-20:123145510502400][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 17:35:01,246][Thread-24:123145515757568][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 17:35:29,292][Thread-27:123145510502400][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 17:35:51,081][Thread-30:123145510502400][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 17:36:05,967][Thread-32:123145515757568][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 18:14:24,633][Thread-3:123145479258112][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 18:14:27,177][Thread-4:123145474002944][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/message/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 394, in get
    all_messages = users_forms.UserMessage.objects.filter(
AttributeError: module 'users.forms' has no attribute 'UserMessage'
[2018-09-28 18:14:44,121][Thread-7:123145474002944][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/message/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 394, in get
    all_messages = users_forms.UserMessage.objects.filter(
AttributeError: module 'users.forms' has no attribute 'UserMessage'
[2018-09-28 18:20:08,986][Thread-1:123145565085696][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/message/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 408, in get
    p = Paginator(all_messages, 5)
NameError: name 'Paginator' is not defined
[2018-09-28 18:46:41,431][Thread-13:123145435373568][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 18:46:55,933][Thread-23:123145440628736][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 18:47:02,745][Thread-25:123145440628736][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 18:47:15,727][Thread-27:123145440628736][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 19:01:33,804][Thread-1:123145499901952][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/home/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sugyil/dashubao/dashubao/mobileurls.py", line 15, in <module>
    ('users.mobileurls', 'users'), namespace="users")),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sugyil/dashubao/apps/users/mobileurls.py", line 26, in <module>
    path('favbook/', M_FavBookView.as_view(), name="users_favbook"),
NameError: name 'M_FavBookView' is not defined
[2018-09-28 19:02:04,082][Thread-4:123145499901952][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/home/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sugyil/dashubao/dashubao/mobileurls.py", line 15, in <module>
    ('users.mobileurls', 'users'), namespace="users")),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sugyil/dashubao/apps/users/mobileurls.py", line 26, in <module>
    path('favbook/', M_FavBookView.as_view(), name="users_favbook"),
NameError: name 'M_FavBookView' is not defined
[2018-09-28 19:02:22,134][Thread-7:123145505157120][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 19:20:13,220][Thread-7:123145589182464][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/favbook/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 446, in get
    favbooks = operation_models.UserFavorite.objects.filter(user=request.user)
AttributeError: module 'operation.models' has no attribute 'UserFavorite'
[2018-09-28 19:20:27,866][Thread-1:123145362186240][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/favbook/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 446, in get
    favbooks = operation_models.UserFavorite.objects.filter(user=request.user)
AttributeError: module 'operation.models' has no attribute 'UserFavorite'
[2018-09-28 19:54:51,858][Thread-3:123145463517184][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 19:54:51,985][Thread-4:123145458262016][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 19:54:52,021][Thread-5:123145463517184][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 19:54:52,033][Thread-6:123145468772352][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 19:54:52,058][Thread-7:123145474027520][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 19:54:52,071][Thread-8:123145458262016][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 19:55:08,533][Thread-15:123145463517184][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 19:55:08,614][Thread-16:123145458262016][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 19:55:08,631][Thread-17:123145458262016][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 19:55:08,638][Thread-18:123145463517184][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 19:55:08,661][Thread-19:123145468772352][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 19:55:08,670][Thread-20:123145474027520][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 19:55:48,115][Thread-25:123145463517184][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 19:57:55,177][Thread-3:123145463930880][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 19:58:07,388][Thread-3:123145562513408][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 19:58:07,514][Thread-5:123145562513408][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 19:58:07,522][Thread-4:123145557258240][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 19:58:07,527][Thread-7:123145573023744][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 19:58:07,538][Thread-6:123145567768576][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 19:58:07,548][Thread-8:123145562513408][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 19:58:13,913][Thread-10:123145562513408][task_id:django.request][log.py:228][WARNING][Not Found: /info-630/oldfenmian/0/630/630s.jpg]
[2018-09-28 19:58:28,828][Thread-14:123145562513408][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 19:58:53,517][Thread-5:123145475432448][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 19:58:56,872][Thread-7:123145475432448][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 19:58:56,954][Thread-9:123145475432448][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 19:58:56,964][Thread-8:123145470177280][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 19:58:56,975][Thread-10:123145480687616][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 19:58:56,984][Thread-11:123145485942784][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 19:58:56,997][Thread-12:123145491197952][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 19:59:59,442][Thread-14:123145475432448][task_id:django.request][log.py:228][WARNING][Not Found: /info-641/oldfenmian/0/641/641s.jpg]
[2018-09-28 20:00:07,584][Thread-18:123145475432448][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 20:08:33,948][Thread-1:123145469267968][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/favbook/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 449, in get
    print(r.novel.get_new_chapter.chapter_name)
AttributeError: 'function' object has no attribute 'chapter_name'
[2018-09-28 20:15:19,011][Thread-1:123145490386944][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/favbook/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 449, in get
    print(r.novel.get_new_chapte['chapter_name'])
AttributeError: 'NovelDetail' object has no attribute 'get_new_chapte'
[2018-09-28 20:15:33,995][Thread-1:123145530187776][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/favbook/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 449, in get
    print(r.novel.get_new_chapte)
AttributeError: 'NovelDetail' object has no attribute 'get_new_chapte'
[2018-09-28 20:16:50,246][Thread-1:123145493364736][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/favbook/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 449, in get
    print(r.novel.get_new_chapter.chapter_name)
AttributeError: 'function' object has no attribute 'chapter_name'
[2018-09-28 20:16:52,786][Thread-3:123145498619904][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/favbook/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 449, in get
    print(r.novel.get_new_chapter.chapter_name)
AttributeError: 'function' object has no attribute 'chapter_name'
[2018-09-28 20:22:47,174][Thread-1:123145523318784][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/favbook/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 458, in get
    'favbooks': favbooks
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'Page' object is not iterable
[2018-09-28 20:22:52,169][Thread-3:123145528573952][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/favbook/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/utils/mixin_utils.py", line 13, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 458, in get
    'favbooks': favbooks
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'Page' object is not iterable
[2018-09-28 21:15:05,414][Thread-10:123145429340160][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:20:39,936][Thread-28:123145429340160][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:21:00,960][Thread-35:123145424084992][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:21:07,283][Thread-38:123145424084992][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:21:49,404][Thread-45:123145429340160][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:21:50,317][Thread-47:123145429340160][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:21:51,459][Thread-49:123145429340160][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:24:31,111][Thread-3:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:25:07,271][Thread-10:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:25:25,296][Thread-17:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:27:21,226][Thread-21:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:33:13,779][Thread-26:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:33:15,778][Thread-28:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 21:33:15,814][Thread-29:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 21:33:15,879][Thread-30:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 21:33:15,886][Thread-31:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 21:33:15,901][Thread-32:123145552830464][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 21:33:15,912][Thread-33:123145558085632][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 21:33:18,286][Thread-36:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /info-631/oldfenmian/0/631/631s.jpg]
[2018-09-28 21:33:22,953][Thread-40:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:33:31,669][Thread-43:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:33:33,539][Thread-45:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 21:33:33,571][Thread-46:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 21:33:33,640][Thread-47:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 21:33:33,650][Thread-50:123145558085632][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 21:33:33,654][Thread-49:123145552830464][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 21:33:33,659][Thread-48:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 21:33:36,188][Thread-52:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /info-630/oldfenmian/0/630/630s.jpg]
[2018-09-28 21:33:40,385][Thread-56:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:33:52,596][Thread-60:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:33:56,060][Thread-62:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 21:33:56,139][Thread-63:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 21:33:56,161][Thread-64:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 21:33:56,167][Thread-65:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 21:33:56,177][Thread-66:123145552830464][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 21:33:56,187][Thread-67:123145558085632][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 21:33:58,592][Thread-69:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/627/627s.jpg]
[2018-09-28 21:33:58,596][Thread-70:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/624/624s.jpg]
[2018-09-28 21:33:58,603][Thread-71:123145552830464][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/623/623s.jpg]
[2018-09-28 21:33:58,613][Thread-72:123145558085632][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/620/620s.jpg]
[2018-09-28 21:33:58,633][Thread-74:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/618/618s.jpg]
[2018-09-28 21:33:58,638][Thread-73:123145563340800][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/619/619s.jpg]
[2018-09-28 21:33:58,650][Thread-75:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/617/617s.jpg]
[2018-09-28 21:33:59,573][Thread-76:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/627/627s.jpg]
[2018-09-28 21:33:59,581][Thread-77:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/624/624s.jpg]
[2018-09-28 21:33:59,586][Thread-80:123145563340800][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/619/619s.jpg]
[2018-09-28 21:33:59,593][Thread-78:123145552830464][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/623/623s.jpg]
[2018-09-28 21:33:59,601][Thread-79:123145558085632][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/620/620s.jpg]
[2018-09-28 21:33:59,623][Thread-81:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/618/618s.jpg]
[2018-09-28 21:33:59,634][Thread-82:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/617/617s.jpg]
[2018-09-28 21:34:00,821][Thread-84:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /info-617/oldfenmian/0/617/617s.jpg]
[2018-09-28 21:34:06,244][Thread-88:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:34:33,635][Thread-93:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /info-641/oldfenmian/0/641/641s.jpg]
[2018-09-28 21:34:33,903][Thread-95:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /info-641/oldfenmian/0/641/641s.jpg]
[2018-09-28 21:34:40,711][Thread-98:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:35:07,850][Thread-101:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:35:11,094][Thread-104:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:35:14,902][Thread-106:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:35:18,696][Thread-108:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 21:35:18,729][Thread-109:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 21:35:18,776][Thread-110:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 21:35:18,789][Thread-111:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 21:35:18,800][Thread-112:123145552830464][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 21:35:18,808][Thread-113:123145558085632][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 21:35:18,882][Thread-114:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 21:35:36,820][Thread-122:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:35:50,535][Thread-128:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:35:54,539][Thread-130:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:35:56,662][Thread-132:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 21:35:56,687][Thread-133:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 21:35:56,792][Thread-134:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 21:35:56,794][Thread-135:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 21:35:56,817][Thread-136:123145552830464][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 21:35:56,824][Thread-137:123145558085632][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 21:35:59,356][Thread-139:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /info-631/oldfenmian/0/631/631s.jpg]
[2018-09-28 21:36:38,955][Thread-146:123145542320128][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 21:37:11,136][Thread-150:123145547575296][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:04:25,071][Thread-3:123145455218688][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:04:29,682][Thread-6:123145449963520][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:04:33,227][Thread-9:123145449963520][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:04:41,951][Thread-12:123145449963520][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:04:48,467][Thread-16:123145455218688][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:04:59,537][Thread-20:123145455218688][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:05:08,418][Thread-23:123145449963520][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:38:06,219][Thread-3:123145580036096][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:39:00,513][Thread-8:123145580036096][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:39:02,415][Thread-9:123145574780928][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/touxian/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sugyil/dashubao/apps/users/views.py", line 511, in get
    'z': z
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['min']' from 'r['min']'
[2018-09-28 22:40:42,463][Thread-15:123145574780928][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:40:45,516][Thread-17:123145580036096][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:41:00,820][Thread-21:123145580036096][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:41:12,017][Thread-24:123145574780928][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:47:48,602][Thread-29:123145574780928][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:48:15,820][Thread-33:123145580036096][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:57:09,143][Thread-1:123145342914560][task_id:django.request][log.py:228][ERROR][Internal Server Error: /users/home/]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sugyil/dashubao/dashubao/mobileurls.py", line 15, in <module>
    ('users.mobileurls', 'users'), namespace="users")),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sugyil/dashubao/apps/users/mobileurls.py", line 24, in <module>
    path('gonggao/', views.M_GonggaoView.as_view(), name="users_gonggao"),
AttributeError: module 'users.views' has no attribute 'M_GonggaoView'
[2018-09-28 22:57:53,742][Thread-3:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:58:48,059][Thread-8:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:59:24,003][Thread-14:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:59:26,732][Thread-17:123145445531648][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:59:27,506][Thread-19:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:59:38,368][Thread-21:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:59:40,180][Thread-23:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:59:40,503][Thread-25:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:59:40,780][Thread-27:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:59:41,271][Thread-29:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 22:59:43,637][Thread-31:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:00:18,735][Thread-33:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:00:26,837][Thread-36:123145445531648][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:00:32,688][Thread-38:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:04:16,588][Thread-40:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:04:31,216][Thread-43:123145445531648][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:04:34,697][Thread-46:123145445531648][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:04:49,475][Thread-50:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:04:56,656][Thread-54:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:05:06,766][Thread-58:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
[2018-09-28 23:05:26,714][Thread-63:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/641/641s.jpg]
[2018-09-28 23:05:26,786][Thread-64:123145445531648][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/638/638s.jpg]
[2018-09-28 23:05:26,814][Thread-65:123145445531648][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/635/635s.jpg]
[2018-09-28 23:05:26,839][Thread-66:123145445531648][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/633/633s.jpg]
[2018-09-28 23:05:26,865][Thread-67:123145445531648][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/631/631s.jpg]
[2018-09-28 23:05:26,884][Thread-68:123145445531648][task_id:django.request][log.py:228][WARNING][Not Found: /oldfenmian/0/630/630s.jpg]
[2018-09-28 23:05:32,017][Thread-72:123145450786816][task_id:django.request][log.py:228][WARNING][Not Found: /media/upload/image/default.png]
